### ISSUE TITLE
Game freeze at startup on some computers.

### ISSUE THREAD

**Issue by JieningYu** [DM-Earth/Cabricality#1]
`[10:52:20] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.8
[10:52:20] [ForkJoinPool-1-worker-8/WARN]: Mod cobblegen uses the version v1.10b33+mc1.18.x which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'v1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[10:52:20] [ForkJoinPool-1-worker-10/WARN]: Mod create uses the version mc1.18.2_v0.5.0+653 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'mc1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[10:52:20] [ForkJoinPool-1-worker-7/WARN]: Mod registrate-fabric uses the version MC1.18.2-1.0.3 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'MC1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[10:52:20] [main/INFO]: Loading 145 mods:
	- ae2 11.1.4
	- agape_space 0.5.15
	- alloy_forgery 2.0.13+1.18
	- architects_palette 2.2
	- architectury 4.5.76
	- badpackets 0.1.2
	- blue_endless_jankson 1.2.1 via jankson
	- caffeineconfig 1.1.0 via sodium-extra
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 6.2.62
	- cobblegen v1.10b33+mc1.18.x
	- com_electronwill_night-config_core 3.6.3 via create
	- com_electronwill_night-config_toml 3.6.3 via create
	- com_github_llamalad7_mixinextras 0.0.10 via extended_drawers
	- com_github_towdium_pinin 1.5.0 via roughly-enough-characters
	- com_google_code_findbugs_jsr305 3.0.2 via create
	- controlling 9.0+21
	- create mc1.18.2_v0.5.0+653
	- createplus 1.0
	- customskinloader 14.14-SNAPSHOT-325
	- dawn 3.3.2
	- de_poiu_apron_apron 2.1.1 via mconfig
	- dripstone_fluid_lib 1.2.0 via milk
	- entityculling 1.5.1
	- extended_drawers 1.3.1+mc.1.18.2
	- fabric 0.57.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.6.2+2373a54560 via fabric
	- fabric-biome-api-v1 8.0.6+651bcc5960 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.22+d7c144a860 via fabric
	- fabric-content-registries-v0 3.1.1+c85f2e3860 via fabric
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
	- fabric-crash-report-info-v1 0.2.1+ee261a3e60 via fabric
	- fabric-data-generation-api-v1 3.0.0+9fcb91d260 via fabric
	- fabric-dimensions-v1 2.1.20+489d6f8260 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.18+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.5.1+6c4e5d0960 via fabric
	- fabric-item-groups-v0 0.3.14+91896a4960 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-language-kotlin 1.8.1+kotlin.1.7.0
	- fabric-lifecycle-events-v1 2.1.0+cc71601c60 via fabric
	- fabric-loot-api-v2 1.1.0+1997ad1260 via fabric
	- fabric-loot-tables-v1 1.1.2+e747827960 via fabric
	- fabric-mining-level-api-v1 2.1.4+cc71601c60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.22+e6b169eb60 via fabric
	- fabric-networking-v0 0.3.9+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.3+032c981d60 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via mconfig
	- fabric-registry-sync-v0 0.9.9+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.5.2+d005b03a60 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-resource-loader-v0 0.5.2+446e059560 via fabric
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.2.1+1f6558e860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.6.3+f4563ac860 via fabric
	- fabric-transitive-access-wideners-v1 1.1.0+e747827960 via fabric
	- fabricloader 0.14.8
	- fake-player-api 0.3.0 via create
	- farmersdelight 1.18.2-0.2.1
	- fiber 0.23.0-2 via patchouli
	- flywheel 1.18-0.6.3.27 via create
	- forge_tags 2.1 via create
	- forgeconfigapiport 3.2.0 via create
	- ftbbackups2 1.0.11
	- ftbchunks 1802.3.6-build.147
	- ftblibrary 1802.3.6-build.123
	- ftbteams 1802.2.6-build.51
	- graphlib 0.2.4+1.18.2 via extended_drawers
	- here-be-no-dragons 1.0.0
	- indium 1.0.6+mc1.18.2
	- indrev 1.14.0-BETA
	- inventoryprofilesnext 1.6.0
	- iris 1.2.4-build.38
	- jankson 4.0.0+j1.2.0 via libgui
	- java 17
	- kibe 1.9.8-BETA+1.18
	- kubejs 1802.5.4-build.516
	- kubejs_create 1802.2.2-build.26
	- lazydfu 0.1.2
	- libblockattributes_core 0.10.0 via indrev
	- libblockattributes_fluids 0.10.0 via indrev
	- libblockattributes_items 0.10.0 via indrev
	- libgui 5.3.2+1.18.2 via indrev
	- libninepatch 1.1.0 via libgui
	- lithium 0.7.10
	- logical_zoom 0.0.14
	- magna 1.7.0-1.18-pre1 via indrev
	- mconfig 1.2.0 via extended_drawers
	- mcwifipnp 1.5.6
	- milk 0.3.2 via create
	- minecraft 1.18.2
	- mm 2.3 via porting_lib
	- modmenu 3.2.3
	- noindium 1.0.2+1.18.2 via ae2
	- notenoughcrashes 4.1.6+1.18.2
	- omega-config 1.2.3-1.18.1 via cobblegen
	- org_anarres_jcpp 1.4.14 via iris
	- org_jetbrains_kotlin_kotlin-reflect 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.3 via fabric-language-kotlin
	- org_joml_joml 1.10.2 via sodium
	- owo 0.7.2+1.18
	- patchouli 1.18.2-66-FABRIC via indrev
	- playerabilitylib 1.5.0 via kibe
	- polylib 1801.0.2-build.13
	- porting_lib 1.1.369-beta+1.18.2-dev.86e4d12 via create
	- promenade 2.6.3
	- reach-entity-attributes 2.1.1 via create
	- reeses-sodium-options 1.4.3+mc1.18.2-build.42
	- registrate-fabric MC1.18.2-1.0.3 via create
	- rhino 1802.1.13-build.175
	- roughly-enough-characters 0.0.5+1.18.2-fabric0.13.3
	- roughlyenoughitems 8.3.510
	- serialization_hooks 0.2.0+1.18.f5d4aa6 via porting_lib
	- sodium 0.4.1+build.15
	- sodium-extra 0.4.5+mc1.18.2-build.42
	- starlight 1.0.2+fabric.89b8d9f
	- step-height-entity-attribute 1.0.0 via indrev
	- team_reborn_energy 2.0.0-beta1 via ae2
	- terraform-shapes-api-v1 2.1.0 via promenade
	- wthit 4.11.0
[10:52:21] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/G:/%e6%a1%8c%e9%9d%a2/%e6%96%b0%e5%bb%ba%e6%96%87%e4%bb%b6%e5%a4%b9/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[10:52:21] [main/INFO]: Compatibility level set to JAVA_11
[10:52:21] [main/INFO]: Compatibility level set to JAVA_17
[10:52:21] [main/INFO]: Loaded configuration file for Lithium: 102 options available, 0 override(s) found
[10:52:21] [main/WARN]: Reference map 'rhino-fabric-refmap.json' for rhino.mixins.json could not be read. If this is a development environment you can ignore this message
[10:52:21] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[10:52:21] [main/INFO]: Loaded configuration file for Sodium Extra: 27 options available, 0 override(s) found
[10:52:22] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[10:52:22] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[10:52:22] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[10:52:23] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[10:52:23] [main/WARN]: @Final field field_22786:Ljava/util/List; in mixins.ipnext.json:MixinScreen from mod inventoryprofilesnext should be final
[10:52:23] [main/WARN]: @Final field field_33815:Ljava/util/List; in mixins.ipnext.json:MixinScreen from mod inventoryprofilesnext should be final
[10:52:23] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=2 on dripstone_fluid_lib.mixins.json:MinecraftClientMixin from mod dripstone_fluid_lib::handler$znc000$dripstone_fluid_lib$handleParticles exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[10:52:26] [main/WARN]: Method overwrite conflict for setTranslation in flywheel.fabric.mixins.json:Matrix4fMixin from mod flywheel, previously written by io.github.fabricators_of_create.porting_lib.mixin.common.Matrix4fMixin. Skipping method.
[10:52:29] [Render thread/WARN]: Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder from mod sodium, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.
[10:52:30] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[10:52:30] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-3.3.39.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:132) ~[authlib-3.3.39.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:44) ~[authlib-3.3.39.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:153) ~[authlib-3.3.39.jar:?]
	at net.minecraft.client.MinecraftClient.createUserApiService(MinecraftClient:680) ~[?:?]
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:424) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:197) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:78) ~[authlib-3.3.39.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-3.3.39.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:113) ~[authlib-3.3.39.jar:?]
	... 8 more
[10:52:30] [Render thread/INFO]: Setting user: Bei_nan
[10:52:30] [Render thread/INFO]: [Agape Space Mod] Initializing
[10:52:30] [Render thread/INFO]: [Agape Space Mod] Planet configs loaded.
[10:52:30] [Render thread/INFO]: [Agape Space Mod] Loading skybox for [agape:venus_clouds]...
[10:52:30] [Render thread/INFO]: [Agape Space Mod]  => [all],[agape_space:textures/environment/venus3.png]
[10:52:30] [Render thread/INFO]: [Agape Space Mod] Loading skybox for [agape:starship_1]...
[10:52:30] [Render thread/INFO]: [Agape Space Mod]  => [all],[agape_space:textures/environment/stars.png]
[10:52:33] [Render thread/WARN]: Encountered duplicate API provider registration for item: minecraft:bucket
[10:52:34] [Render thread/WARN]: Encountered duplicate API provider registration for item: minecraft:bucket
[10:52:34] [Render thread/WARN]: Encountered duplicate API provider registration for item: minecraft:glass_bottle
[10:52:34] [Render thread/WARN]: Encountered duplicate API provider registration for item: minecraft:glass_bottle
[10:52:34] [Render thread/WARN]: Encountered duplicate API provider registration for item: minecraft:bucket
[10:52:36] [Render thread/INFO]: Industrial Revolution has initialized.
[10:52:37] [Render thread/INFO]: Trying to read config file...
[10:52:37] [Render thread/INFO]: A config file was found, loading it..
[10:52:37] [Render thread/INFO]: Successfully loaded config file.
[10:52:37] [Render thread/WARN]: Encountered duplicate API provider registration for item: minecraft:glass_bottle
[10:52:37] [Render thread/INFO]: Looking for KubeJS plugins...
[10:52:37] [Render thread/INFO]: Found plugin source kubejs
[10:52:37] [Render thread/INFO]: Found plugin source ftbchunks
[10:52:37] [Render thread/INFO]: Found plugin source kubejs_create
[10:52:37] [Render thread/INFO]: Done in 18.79 ms
[10:52:37] [Render thread/INFO]: Loaded common.properties
[10:52:44] [FTB Backups Config Watcher 0/INFO]: Config at *path*\.minecraft\versions\Cabricality\config\ftbbackups2.json has changed, reloaded!
`

From someone who has this problem, the performance impact is very low when freezing. (ex. 1~2% cpu)

**Comment by JieningYu** [comment]
Note: The log is from a person who has this strange issue.

**Comment by Flamarine** [comment]
I'm having the same issue. Hooray.

**Comment by JieningYu** [comment]
So what caused this

**Comment by JieningYu** [comment]
I tried with java18, java17, hmcl and polymc, they all works fine. Can't reproduce.

**Comment by Flamarine** [comment]
using multimc and it just fucking freezes.

**Comment by JieningYu** [comment]
try remove kubejs?
(but i don't think it's a kubejs issue)

**Comment by Flamarine** [comment]
using pcl2 and met the same issue.
what jdk are you using?

**Comment by JieningYu** [comment]
[azulu](https://www.azul.com/downloads/?version=java-17-lts&package=jdk)
tried using 17 and 19. Both worked.

**Comment by Flamarine** [comment]
I tried GraalVM (17.0.3) and Microsoft JDK (17.0.2), both not working

**Comment by JieningYu** [comment]
there must be a certain mod caused it.

**Comment by Flamarine** [comment]
![image](https://user-images.githubusercontent.com/62203463/179893859-bb7152c2-c481-4d32-9873-807f922af3c1.png)

Well I tried to install Mod Loading Screen to find out which mod causes the game freezes and it seems that the game freezes when loading KubeJS.

Maybe it's caused by that many scripts?

**Comment by Flamarine** [comment]
note that I have never touched JavaScript or any related scripting engine like Nashorn and Rhino and doesn't know its efficiency. The only scripting language I know a little is TypeScript.

**Comment by JieningYu** [comment]
Try removing the scripts

**Comment by Flamarine** [comment]
Nope, still freezes the game
Yet more randomly

**Comment by JieningYu** [comment]
So this is not caused by the scripts but Kubejs itself.

**Comment by Flamarine** [comment]
yep, but sometimes loading Create also freezes the game, but loading KubeJS *always* does so

**Comment by JieningYu** [comment]
loading Create freezes for a while then start up but KubeJS freeze forever by some testing.

**Comment by JieningYu** [comment]
try update kubejs and rhino.

**Comment by Flamarine** [comment]
nope, still freezes

**Comment by JieningYu** [comment]
What about a instance with only kubejs

**Comment by ghost** [comment]
这是kjs自己的问题，可能是rhino跟kjs的版本匹配不对劲，在魔改群里也有很多人遇到了，说是这两个版本就没问题（当然这是forge的，fabric就不清楚了，相同版本试试看？）：
![@R$E7 ~BSLTD0ZF1WI0DXU8](https://user-images.githubusercontent.com/76616758/180599388-76b39b30-a16f-4449-9c5e-3679d61ee1f0.png)

**Comment by ghost** [comment]
还有人说是java问题，不能用jdk里包含的jre，换普通的jre就可以。

**Comment by JieningYu** [comment]
这个每个人的情况不一样，有许多不确定性

**Comment by JieningYu** [comment]
> 这是kjs自己的问题，可能是rhino跟kjs的版本匹配不对劲，在魔改群里也有很多人遇到了，说是这两个版本就没问题（当然这是forge的，fabric就不清楚了，相同版本试试看？）： ![@R$E7 ~BSLTD0ZF1WI0DXU8](https://user-images.githubusercontent.com/76616758/180599388-76b39b30-a16f-4449-9c5e-3679d61ee1f0.png)

可以通过这个解决

**Comment by JieningYu** [comment]
Should be fixed.
