### ISSUE TITLE
JEI更多选项崩溃

### ISSUE THREAD

**Issue by jiang131072** [DM-Earth/Cabricality#123]
类型转换错误。
在背包界面JEI菜单中选择“更多选项”，直接崩溃。无额外模组和光影添加。
```
错误日志：
---- Minecraft 崩溃报告 ----
崩溃类型： Rendering screen
java.lang.ClassCastException: class java.lang.Float cannot be cast to class java.lang.Integer (java.lang.Float and java.lang.Integer are in module java.base of loader 'bootstrap')
	at org.spongepowered.asm.synthetic.args.Args$14.set(Args$14.java)
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen.args$cao000$renderOverlayBackground(ClothConfigScreen.java:524)
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen.method_25394(ClothConfigScreen.java:242)
	at net.minecraft.class_757.method_3192(class_757.java:877)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:527)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
```

**Comment by JieningYu** [comment]
整合包无JEI,使用的为REI.
请尝试回退quilt loader版本 / rei版本

**Comment by Gebardensprache** [comment]
无法解决且不是整合包问题。
