### ISSUE TITLE
Cabricality mod crashes the game when opening REI's options

### ISSUE THREAD

**Issue by Ratismal** [DM-Earth/Cabricality#132]
On Cabricality 0.2.4, opening REI's options crashes the game. I did a binary search on the mods to determine what the conflict was, and it turns out to be the Cabricality mod itself. Removing the mod lets the REI options work properly.

Relevant logs:
```
[Render thread/INFO] Cabricality has initialized in 18196ms! âš™ï¸�
	at net.minecraft.class_757.method_3192(class_757.java:886)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:517)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.ClassCastException: class java.lang.Float cannot be cast to class java.lang.Integer (java.lang.Float and java.lang.Integer are in module java.base of loader 'bootstrap')
	at org.spongepowered.asm.synthetic.args.Args$12.set(Args$12.java)
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen.args$clf000$cabricality$renderOverlayBackground(ClothConfigScreen.java:524)
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen.method_25394(ClothConfigScreen.java:242)
	at net.minecraft.class_757.method_3192(class_757.java:877)
	... 10 more
[Render thread/FATAL] Reported exception thrown!
---- Minecraft Crash Report ----
// Don't do that.

Time: 5/29/23, 4:36 PM
Description: Rendering screen

java.lang.ClassCastException: class java.lang.Float cannot be cast to class java.lang.Integer (java.lang.Float and java.lang.Integer are in module java.base of loader 'bootstrap')
	at org.spongepowered.asm.synthetic.args.Args$12.set(Args$12.java)
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen.args$clf000$cabricality$renderOverlayBackground(ClothConfigScreen.java:524)
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen.method_25394(ClothConfigScreen.java:242)
	at net.minecraft.class_757.method_3192(class_757.java:877)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:517)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
```

I honestly have no idea what the cabricality mod could be doing to cause this.

**Comment by Ratismal** [comment]
Looked a bit at the mod's mixins and it seems like the culprit is this line: https://github.com/DM-Earth/Cabricality/blob/bc0b99bf0cde381c5f8db9cf73f65c07479b9f7a/src/main/java/com/dm/earth/cabricality/mixin/client/cloth/ClothConfigScreenAnimator.java#L23

**Comment by JieningYu** [comment]
based

**Comment by KrLite** [comment]
Solved.
