### ISSUE TITLE
Can't connect Client with Server

### ISSUE THREAD

**Issue by qwerty3173** [DM-Earth/Cabricality#54]
localhost本地连接
``
[2022-09-29-3.log](https://github.com/DM-Earth/Cabricality/files/9670794/2022-09-29-3.log)
``
[minecraft-exported-logs-2022-09-29T01-12-28.log](https://github.com/DM-Earth/Cabricality/files/9670805/minecraft-exported-logs-2022-09-29T01-12-28.log)

[01:09:02] [Netty Client IO #0/INFO]: Connected to a vanilla server. Catching up missing behaviour.
Sep 29, 2022 1:09:03 AM com.replaymod.replaystudio.lib.viaversion.protocols.protocol1_13to1_12_2.blockconnections.ConnectionData init
INFO: Loading block connection mappings ...
[01:09:04] [Netty Client IO #0/ERROR]: Exception occurred in netty pipeline
io.netty.handler.codec.DecoderException: io.netty.handler.codec.EncoderException: java.io.IOException: Root tag must be a named compound tag
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:477) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) [netty-all-4.1.68.Final.jar:4.1.68.Final]

**Comment by JieningYu** [comment]
<img width="516" alt="image" src="https://user-images.githubusercontent.com/61787533/192940103-e4cf2218-a21b-49a9-950f-eabbe7d84131.png">
You only loaded Quilt Loader itself in your server.
